[package]
name = "wallpaper"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0"
ntex = { version = "4.0.0-beta.4", default-features = false, features = ["openssl", "ws"] }
sonic-rs = "0"

[target.'cfg(target_os = "macos")'.dependencies]
cidre = { version = "0", default-features = false, features = ["app", "blocks", "ca", "macos_27_0"] }

[target."cfg(windows)".dependencies]
futures = "0"
windows = {
  version = "0",
  features = [
    "Foundation",
    "Storage_Streams",
    "System_UserProfile",
    "Win32_System_WinRT",
    "Win32_UI_WindowsAndMessaging",
  ]
}

[profile.release]
debug = false
strip = true
lto = true
panic = "abort"
codegen-units = 1
